stages:
  - publish

publish:
  stage: publish
  image: node:22-alpine
  only:
    - main
  before_script:
    - apk add --no-cache git
    - npm install
  script:
    - npm run build
    - npx semantic-release
