/**
 * README.md 동적 생성기
 *
 * 사용자가 선택한 스택/옵션에 맞게 프로젝트 README를 생성한다.
 */
import path from 'node:path';
import fs from 'fs-extra';
import { getStackCategory, STACKS, type StackValue } from '../constants.js';
import type { UserChoices, StackConfig } from '../prompts/types.js';

/**
 * 사용자 선택에 맞는 프로젝트 README.md를 동적으로 생성한다.
 *
 * Tech Stack, Quick Start, Docker, AI Agent, Graphify 등의 섹션을 포함한다.
 *
 * @param projectDir - 프로젝트 루트 디렉토리 절대 경로
 * @param choices - 사용자 선택 결과
 */
export async function generateReadme(projectDir: string, choices: UserChoices): Promise<void> {
  const lines: string[] = [];

  lines.push(`# ${choices.projectName}`);
  lines.push('');
  lines.push('> Generated by [create-harness](https://github.com/your-team/create-harness)');
  lines.push('');

  // Tech Stack 테이블
  if (choices.repoStructure === 'monorepo' && choices.stacks) {
    lines.push('## Tech Stack');
    lines.push('');
    lines.push('| App | Stack | Port |');
    lines.push('|-----|-------|------|');
    for (const s of choices.stacks) {
      const app = getAppName(s.stack);
      const label = getStackLabel(s.stack);
      const port = getDefaultPort(s.stack);
      lines.push(`| \`apps/${app}\` | ${label} | ${port} |`);
    }
    lines.push('');
  } else {
    lines.push(`## Tech Stack`);
    lines.push('');
    lines.push(`- **Stack**: ${getStackLabel(choices.stack)}`);
    if (choices.language) lines.push(`- **Language**: ${choices.language}`);
    if (choices.architecture) lines.push(`- **Architecture**: ${choices.architecture}`);
    if (choices.packageManager) lines.push(`- **Package Manager**: ${choices.packageManager}`);
    if (choices.linter) lines.push(`- **Linter**: ${choices.linter}`);
    if (choices.style) lines.push(`- **Styling**: ${choices.style}`);
    if (choices.stateManagement) lines.push(`- **State Management**: ${choices.stateManagement}`);
    if (choices.orm) lines.push(`- **ORM**: ${choices.orm}`);
    if (choices.database && choices.database !== 'none') lines.push(`- **DB**: ${choices.database}`);
    if (choices.testFramework) lines.push(`- **Test**: ${choices.testFramework}`);
    lines.push('');
  }

  // Quick Start
  lines.push('## Quick Start');
  lines.push('');
  lines.push('```bash');
  if (choices.autoInstall) {
    lines.push('# 의존성은 이미 설치됨');
  } else if (choices.packageManager) {
    lines.push(`# 의존성 설치`);
    lines.push(`${choices.packageManager} install`);
    lines.push('');
  }
  lines.push('# 개발 서버');
  lines.push(getDevCommand(choices));
  lines.push('```');
  lines.push('');

  // 모노레포 구조
  if (choices.repoStructure === 'monorepo' && choices.stacks) {
    lines.push('## Scripts');
    lines.push('');
    lines.push('| Command | Description |');
    lines.push('|---------|-------------|');
    lines.push('| `pnpm dev` | 전체 개발 서버 |');
    lines.push('| `pnpm build` | 전체 빌드 |');
    lines.push('| `pnpm lint` | 전체 린트 |');
    lines.push('| `pnpm test` | 전체 테스트 |');
    lines.push('');

    // 앱별 상세
    lines.push('## Apps');
    lines.push('');
    for (const s of choices.stacks) {
      const app = getAppName(s.stack);
      lines.push(`### ${app} (${getStackLabel(s.stack)})`);
      lines.push('');
      if (s.architecture) lines.push(`- **아키텍처**: ${s.architecture}`);
      if (s.style) lines.push(`- **스타일**: ${s.style}`);
      if (s.stateManagement) lines.push(`- **상태관리**: ${s.stateManagement}`);
      if (s.orm) lines.push(`- **ORM**: ${s.orm}`);
      if (s.database && s.database !== 'none') lines.push(`- **DB**: ${s.database}`);
      if (s.apiStyle) lines.push(`- **API**: ${s.apiStyle}`);
      if (s.apiDocs && s.apiDocs !== 'none') lines.push(`- **API 문서**: ${s.apiDocs}`);
      if (s.testFramework) lines.push(`- **테스트**: ${s.testFramework}`);
      lines.push('');
    }
  }

  // Docker
  if (choices.docker) {
    lines.push('## Docker');
    lines.push('');
    lines.push('```bash');
    lines.push('# 전체 실행');
    lines.push('docker compose up');
    lines.push('');
    lines.push('# 백그라운드 실행');
    lines.push('docker compose up -d');
    lines.push('```');
    lines.push('');
  }

  // AI Agent
  lines.push('## AI Agent');
  lines.push('');
  lines.push(`이 프로젝트는 **${getAgentLabel(choices.agent)}** 에이전트 룰이 설정되어 있습니다.`);
  lines.push('');

  // Graphify
  if (choices.graphify) {
    lines.push('## Knowledge Graph (Graphify)');
    lines.push('');
    lines.push('이 프로젝트는 [Graphify](https://github.com/safishamsi/graphify)로 코드베이스의 Knowledge Graph가 생성되어 있습니다.');
    lines.push('AI 에이전트가 코드를 탐색할 때 파일을 하나씩 읽는 대신 그래프를 먼저 조회하여 **토큰 사용량을 대폭 절감**합니다.');
    lines.push('');
    lines.push('### 어떻게 동작하나요?');
    lines.push('');
    lines.push('1. `graphify update .` 로 코드를 AST 분석하여 함수/클래스/모듈 간 관계를 그래프로 만듭니다');
    lines.push('2. AI 에이전트가 질문을 받으면 `graphify query` 로 관련 코드만 정확히 찾습니다');
    lines.push('3. git commit 시 post-commit hook으로 **자동 갱신**됩니다 (LLM 토큰 소비 없음)');
    lines.push('');
    lines.push('### 자주 쓰는 명령어');
    lines.push('');
    lines.push('```bash');
    lines.push('# 코드베이스에서 질문으로 검색');
    lines.push('graphify query "health endpoint"');
    lines.push('');
    lines.push('# 두 개념 사이의 관계 경로 찾기');
    lines.push('graphify path "handler" "Health"');
    lines.push('');
    lines.push('# 특정 개념의 역할과 연결 관계 설명');
    lines.push('graphify explain "handler"');
    lines.push('');
    lines.push('# 그래프 수동 갱신 (코드만 AST 분석, LLM 키 불필요)');
    lines.push('graphify update .');
    lines.push('');
    lines.push('# 그래프 전체 재생성 (docs/이미지 포함, LLM 키 필요)');
    lines.push('graphify .');
    lines.push('```');
    lines.push('');
    lines.push('### 생성되는 파일');
    lines.push('');
    lines.push('| 파일 | 설명 |');
    lines.push('|------|------|');
    lines.push('| `graphify-out/graph.json` | Knowledge Graph 데이터 |');
    lines.push('| `graphify-out/GRAPH_REPORT.md` | 전체 아키텍처 리포트 |');
    lines.push('| `graphify-out/graph.html` | 인터랙티브 그래프 시각화 (브라우저로 열기) |');
    lines.push('| `.graphifyrc` | Graphify 설정 |');
    lines.push('');
    lines.push('### AI 에이전트와 연동');
    lines.push('');
    lines.push(`이 프로젝트는 **${getAgentLabel(choices.agent)}**와 연동되어 있어 에이전트가 자동으로 graphify를 활용합니다.`);
    lines.push('코드 관련 질문을 하면 에이전트가 먼저 `graphify query`를 실행하여 정확한 파일을 찾고,');
    lines.push('불필요한 파일 탐색 없이 토큰을 절약합니다.');
    lines.push('');
    lines.push('> 💡 `graphify-out/graph.html`을 브라우저에서 열면 프로젝트 전체 구조를 시각적으로 확인할 수 있습니다.');
    lines.push('');
  }

  // Environment Variables
  lines.push('## Environment Variables');
  lines.push('');
  lines.push('```bash');
  lines.push('cp .env.example .env');
  lines.push('```');
  lines.push('');

  await fs.writeFile(path.join(projectDir, 'README.md'), lines.join('\n'));
}

// ─── Helpers ───

function getStackLabel(stack: StackValue): string {
  const all = [
    ...STACKS.frontend.items,
    ...STACKS.backend.items,
    ...STACKS.blockchain.items,
    // ...STACKS.mobile.items,
  ];
  return all.find((s) => s.value === stack)?.label ?? stack;
}

function getAgentLabel(agent: string): string {
  const map: Record<string, string> = {
    claude: 'Claude Code', cursor: 'Cursor', windsurf: 'Windsurf',
    cline: 'Cline', copilot: 'GitHub Copilot', aider: 'Aider', gemini: 'Gemini CLI',
  };
  return map[agent] ?? agent;
}

function getAppName(stack: string): string {
  const map: Record<string, string> = {
    'nextjs-app': 'web', 'nextjs-pages': 'web', 'react-vite': 'web',
    'vue-vite': 'web', 'nuxt': 'web', 'sveltekit': 'web', 'angular': 'web',
    'go-gin': 'api', 'go-echo': 'api', 'java-spring': 'api',
    'python-fastapi': 'api', 'python-django': 'api',
    'node-express': 'api', 'node-nestjs': 'api', 'node-hono': 'api',
    'solidity-hardhat': 'contracts', 'solidity-foundry': 'contracts',
    'solana-anchor': 'contracts', 'move-sui': 'contracts', 'move-aptos': 'contracts',
    'ton-tact': 'contracts', 'cosmwasm': 'contracts',
    'react-native': 'mobile', 'flutter': 'mobile',
  };
  return map[stack] ?? stack;
}

function getDefaultPort(stack: StackValue): string {
  const category = getStackCategory(stack);
  if (category === 'frontend') return '3000';
  if (category === 'node-backend') return '3000';
  if (category === 'go') return '8080';
  if (category === 'python') return '8000';
  if (category === 'java') return '8080';
  return '-';
}

function getDevCommand(choices: UserChoices): string {
  if (choices.repoStructure === 'monorepo') return 'pnpm dev';
  const pm = choices.packageManager;
  const category = getStackCategory(choices.stack);
  if (category === 'go') return 'go run ./cmd/server';
  if (category === 'python') return 'uvicorn app.main:app --reload';
  if (category === 'java') return choices.buildTool === 'maven' ? 'mvn spring-boot:run' : 'gradle bootRun';
  return pm ? `${pm} run dev` : 'npm run dev';
}
